language: node_js
node_js:
  - "8"

before_script:
  - npm run build
  - cp -a ./build/ ./examples/build/

script:
  - npm test

after_success:
  - npm run coverage

deploy:
  provider: surge
  project: ./examples/
  domain: betweenjs.js.org
  on:
    all_branches: true
